core/blog/api/v1/urls.py
from . import views
from rest_framework.routers import DefaultRouter

app_name = "api-v1"
router = DefaultRouter()
router.register(r"post", views.PostModelViewSet, basename="post")
router.register(r"category", views.CategoryModelViewSet, basename="category")
urlpatterns = router.urls

# urlpatterns = [
#     # path("post/", PostList, name="post-list"),
#     # path("post/<int:id>/", PostDetail, name="post-detail"),
#     # path('post/', views.PostList.as_view(), name="post-list"),
#     # path("post/<int:pk>/", views.PostDetail.as_view(), name="post-detail"),
#     path("post/", views.PostViewSet.as_view({'get':'list', 'post':'create'}), name="post-list"),
#     path("post/<int:pk>/", views.PostViewSet.as_view({'get':'retrieve', 'put':'update', 'patch':'partial_update', 'delete':'destroy'}), name="post-detail"),
# ]

core/blog/urls.py
from django.urls import path, include
from .views import (
    IndexView,
    ArticleListView,
    post_Detail_view,
    PostsEditView,
    PostsCreateView,
    PostDeleteView,
    ArticleListApiView,
)

app_name = "blog"

urlpatterns = [
    # path("", indexView, name="funtion_test"),
    path("index/", IndexView.as_view(), name="index"),
    path("posts/", ArticleListView.as_view(), name="post_list"),
    path("posts/api/", ArticleListApiView.as_view(), name="post_list_api"),
    path("post/<int:pk>/", post_Detail_view.as_view(), name="post-detail"),
    path("post/create/", PostsCreateView.as_view(), name="post-create"),
    path("post/<int:pk>/edit", PostsEditView.as_view(), name="post-edit"),
    path("post/<int:pk>/delete", PostDeleteView.as_view(), name="post-delete"),
    path("api/v1/", include("blog.api.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Blog API ",
        default_version="v1",
        description="this is a api for my django test project",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(
            email="firoozjaieehsan@gmail.com",
        ),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("blog/", include("blog.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api-docs/", include_docs_urls(title="api_sample")),
    path(
        "swagger/outpot.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

# serving static and media files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

# Create your models here.

# get user model object
User = get_user_model()


class Post(models.Model):
    """this is the to define posts for blog app"""

    author = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    title = models.CharField(max_length=250)
    content = models.TextField()
    status = models.BooleanField()
    category = models.ForeignKey("Category", on_delete=models.SET_NULL, null=True)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField()

    def __str__(self):
        return self.title

    def get_snippet(self):
        return self.content[:5]

    def get_absolute_api_url(self):
        return reverse("blog:api-v1:post-detail", kwargs={"pk": self.pk})


class Category(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

core/blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "category", "status", "published_date"]

core/blog/api/v1/views.py
from .serializers import PostSerializer, CategorySerializer
from ...models import Post, Category
from rest_framework.permissions import (
    IsAuthenticatedOrReadOnly,
    IsAuthenticated,
)
from rest_framework import viewsets
from .permissions import IsOwnerOrReadOnly
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from .pegination import DefaultPagination

# create function based view
"""
@api_view(["GET", "POST"])
@permission_classes([IsAuthenticated])
def PostList(request):
    if request.method == "GET":
        posts = Post.objects.filter(status=True)
        serializer = PostSerializer(posts, many=True)
        return Response(serializer.data)
    elif request.method == "POST":
        serializer = PostSerializer(data = request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)

@api_view(["GET", "PUT", "DELETE"])
@permission_classes([IsAuthenticatedOrReadOnly])
def PostDetail(request, id):
    post = get_object_or_404(Post,pk=id, status = True)
    if request.method == "GET":
        serializer = PostSerializer(post)
        return Response(serializer.data)
    elif request.method =="PUT":
        serializer = PostSerializer(post, data = request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
    elif request.method =="DELETE":
        post.delete()
        return Response({"detail":"Item removed successfully"},status=status.HTTP_204_NO_CONTENT)
        """

# example for class based rest views
'''
class PostList(APIView):
    """getting a list of posts and creating new post"""
    permission_classes = [IsAuthenticated]
    serializer_class = PostSerializer
    def get(self, request):
        """retrieves a list of posts"""
        posts = Post.objects.filter(status=True)
        serializer = PostSerializer(posts, many=True)
        return Response(serializer.data)
    def post(self, request):
        """creates a new post with provided data"""
        serializer = PostSerializer(data = request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)
        '''


'''
class PostDetail(APIView):
    """getting a post, updating it and deleting it"""
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = PostSerializer

    def get(self, request , id):
        """retrieves a single post"""
        post = get_object_or_404(Post,pk=id, status = True)
        serializer = self.serializer_class(post)
        return Response(serializer.data)
    def put(self, request , id):
        """updates a single post"""
        post = get_object_or_404(Post,pk=id, status = True)
        serializer = PostSerializer(post, data = request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

    def delete(self, request, id):
        """delete a single post"""
        post = get_object_or_404(Post,pk=id, status = True)
        post.delete()
        return Response({"detail":"Item removed successfully"},status=status.HTTP_204_NO_CONTENT)
    '''

# Example for GenericAPIView for class based views
# class PostList(ListCreateAPIView):
#     """getting a list of posts and creating new post"""
#     permission_classes = [IsAuthenticated]
#     serializer_class = PostSerializer
#     queryset = Post.objects.filter(status=True)
# class PostDetail(RetrieveUpdateDestroyAPIView):
#     """getting a post, updating it and deleting it"""
#     permission_classes = [IsAuthenticatedOrReadOnly]
#     serializer_class = PostSerializer
#     queryset = Post.objects.filter(status=True)


# Example for viewSet in CBV
class PostModelViewSet(viewsets.ModelViewSet):
    """getting a list of posts and creating new post"""

    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    serializer_class = PostSerializer
    queryset = Post.objects.filter(status=True).order_by("published_date")
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = {
        "category": ["exact", "in"],
        "author": ["exact"],
        "status": ["exact"],
    }
    search_fields = ["title", "content"]
    ordering_fields = ["published_date"]
    pagination_class = DefaultPagination


class CategoryModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = CategorySerializer
    queryset = Category.objects.all()

core/blog/views.py
from django.views.generic import TemplateView, DetailView
from .models import Post
from django.views.generic.list import ListView
from rest_framework.decorators import api_view
from .forms import PostForm
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
)
from rest_framework.response import Response

# Create your views here.

# def indexView(request):
#     return render(request,'index.html')


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(request, **kwargs):
        context = super().get_context_data(**kwargs)
        name = "Ehsan"
        context["name"] = name
        context["posts"] = Post.objects.all()
        return context


class ArticleListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    permission_required = "blog.view_post"
    model = Post
    # queryset = Post.objects.filter(status=True).order_by('-created_at')
    context_object_name = "posts"
    # paginate_by = 2
    ordering = "-id"
    # def get_queryset(self):
    #     posts = Post.objects.filter(status=True)
    #     return posts


class post_Detail_view(LoginRequiredMixin, DetailView):
    model = Post


"""
class PostsCreateView(FormView):
    template_name = "contact.html"
    form_class = PostForm
    success_url = "/blog/posts/"

    def get_template_names(self):
        template = get_template(self.template_name)
        print("Template found at:", template.origin)
        return [self.template_name]
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    """


class PostsCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    # fields = ['author', 'title','content', 'category', 'status', 'published_date']
    success_url = "/blog/posts/"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostsEditView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    success_url = "/blog/posts/"


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = "/blog/posts/"


class ArticleListApiView(TemplateView):
    template_name = "blog/post_list_api.html"


@api_view(["GET"])
def Post_ListView(request):
    return Response({"name": "Ehsan"})

core/templates/blog/post_confirm_delete.html
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <h1>ehsan</h1>
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>

            {{form}}
            <input type="submit" value="Confirm">
        </form>
    </body>
</html>

core/templates/blog/post_detail.html
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>{{ object.title }}</h1>
        <br>
        <small>{{ object.author}} - {{ object.published_date }} </small>
        <p> {{object.content}}</p>
    </body>
</html>

core/templates/blog/post_form.html
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <h1>ehsan</h1>
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="save">
        </form>
    </body>
</html>

core/templates/blog/post_list.html
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>blog post</h1>
        {%for post in posts%}

        <li>
            <a href="{% url 'blog:post-detail' pk=post.id%}"> <h2> {{post.id}}-{{post.title}} </h2> </a>
            <br>
            <a href="{% url 'blog:post-edit' pk=post.id%}">edit</a>
            <a href="{% url 'blog:post-delete' pk=post.id%}">delete</a>
            <br>
            <small>{{ post.author.first_name}} - {{ post.published_date }} </small>

        </li>

        {% endfor %}
        {% for contact in page_obj %}
        {# Each "contact" is a Contact model object. #}
        {{ contact.full_name|upper }}<br>
        ...
    {% endfor %}
    
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
        
    </body>
</html>

core/templates/blog/post_list_api.html
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>blog post</h1>
        <ol id = "post_wrapper">
        <!-- <li>
            <a href=""> <h2> - </h2> </a>
        </li> -->
        </ol>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $.get('/blog/api/v1/post/',  // url
            function (data, textStatus, jqXHR) {  // success callback
                wrapper = $('#post_wrapper')
                for (post of data.results){
                    wrapper.append(`<li><a href= "${post.absolute_url}"> <h2>${post.title}</h2></a></li>`)
                // alert('status: ' + textStatus + ', data:' + data);
                // console.log(data);
                }

        });
    </script>

    </body>
</html>